package org.chijai.day10.session2;
import java.util.*;

/**
 * ============================================================================
 *  Count Primes (LeetCode 204)
 * ============================================================================
 *
 * Difficulty:
 *      Medium
 *
 * Tags:
 *      Math
 *      Prime Numbers
 *      Sieve of Eratosthenes
 *      Array
 *
 * Official Link:
 *      https://leetcode.com/problems/count-primes/
 *
 * ----------------------------------------------------------------------------
 * PROBLEM
 * ----------------------------------------------------------------------------
 *
 * Given an integer n, return the number of prime numbers that are
 * strictly less than n.
 *
 * Examples
 *
 * n = 10
 * answer = 4
 * primes:
 * 2 3 5 7
 *
 * n = 0
 * answer = 0
 *
 * n = 1
 * answer = 0
 *
 * Constraints
 *
 * 0 <= n <= 5 * 10^6
 *
 * ============================================================================
 *
 *                     🔵 CORE PATTERN OVERVIEW
 *
 * ============================================================================
 *
 * Pattern Name
 * ------------
 * Sieve of Eratosthenes
 *
 * Problem Archetype
 * -----------------
 * Pre-computation by eliminating impossible candidates.
 *
 * Instead of testing each number independently,
 * we eliminate composite numbers in bulk.
 *
 * Core Invariant
 * --------------
 * Before processing prime p,
 * every multiple of every smaller prime
 * has already been marked composite.
 *
 * Therefore,
 * when we encounter an unmarked number,
 * it MUST be prime.
 *
 * Why It Works
 * ------------
 * Every composite number has a smallest prime factor.
 *
 * That smallest prime factor will eventually process
 * and mark the composite.
 *
 * Therefore every composite gets removed exactly
 * before it could ever be counted as prime.
 *
 * Recognition Signals
 * -------------------
 * Use this pattern when:
 *
 * ✓ Need ALL primes up to N
 * ✓ Need prime count
 * ✓ Need repeated prime queries
 * ✓ Constraints are large
 * ✓ O(N√N) is too slow
 *
 * Avoid When
 * ----------
 * Need primality of only ONE huge number.
 *
 * Then trial division,
 * Miller-Rabin,
 * or Pollard Rho may be better.
 *
 * Difference vs Trial Division
 * ----------------------------
 *
 * Trial Division
 *
 *     Check every number individually.
 *
 * Time:
 *
 *     O(N√N)
 *
 * Sieve
 *
 *     Mark multiples once.
 *
 * Time:
 *
 *     O(N log log N)
 *
 * Huge improvement.
 *
 * ============================================================================
 *
 *                     🟢 MENTAL MODEL
 *
 * ============================================================================
 *
 * Imagine numbers written on paper.
 *
 * 2
 * 3
 * 4
 * 5
 * 6
 * 7
 * ...
 *
 * Nobody knows whether a number is prime.
 *
 * Initially every number >=2 is assumed prime.
 *
 * Whenever we discover a prime,
 * we immediately eliminate all its multiples.
 *
 * Example
 *
 * Start
 *
 * 2 3 4 5 6 7 8 9 10
 *
 * Prime = 2
 *
 * remove
 *
 * 4 6 8 10 ...
 *
 * Remaining
 *
 * 2 3 5 7 9
 *
 * Prime = 3
 *
 * remove
 *
 * 9
 *
 * Remaining
 *
 * 2 3 5 7
 *
 * Every remaining number is prime.
 *
 * ============================================================================
 *
 *                     🟢 INVARIANTS
 *
 * ============================================================================
 *
 * Invariant 1
 * -----------
 *
 * isPrime[x] == true
 *
 * means
 *
 * "No processed prime divides x."
 *
 * NOT
 *
 * "We have already proven x is prime."
 *
 * That distinction is important.
 *
 * ------------------------------------------------------------
 *
 * Invariant 2
 *
 * Once a number becomes false,
 * it NEVER becomes true again.
 *
 * Marking is monotonic.
 *
 * ------------------------------------------------------------
 *
 * Invariant 3
 *
 * Every composite number has
 * a smallest prime factor.
 *
 * Therefore
 *
 * every composite will eventually
 * be marked.
 *
 * ------------------------------------------------------------
 *
 * Invariant 4
 *
 * When processing p,
 * all composites generated by
 * smaller primes
 * are already removed.
 *
 * Therefore
 *
 * if p is still true,
 * p is prime.
 *
 * ------------------------------------------------------------
 *
 * Invariant 5
 *
 * We only need to sieve until
 *
 * p * p < n
 *
 * because every composite larger than
 * sqrt(n)
 *
 * already has a smaller factor.
 *
 * ============================================================================
 *
 * Meaning of Variables
 *
 * n
 * ----
 * Upper exclusive bound.
 *
 * isPrime[]
 * ----------
 * Candidate status.
 *
 * true
 *
 * still alive.
 *
 * false
 *
 * proven composite.
 *
 * p
 * -
 * Current discovered prime.
 *
 * multiple
 * --------
 * Numbers eliminated by p.
 *
 * ============================================================================
 *
 * Allowed Moves
 *
 * ✓ Visit numbers left to right.
 *
 * ✓ Skip already removed numbers.
 *
 * ✓ Remove multiples.
 *
 * ============================================================================
 *
 * Forbidden Moves
 *
 * ✗ Count before removing composites.
 *
 * ✗ Restart marking from 2*p.
 *
 * ✗ Process beyond sqrt(n).
 *
 * ============================================================================
 *
 * Why Starting From p*p Works
 *
 * Suppose
 *
 * p = 7
 *
 * Multiples:
 *
 * 14
 * 21
 * 28
 * 35
 * 42
 * 49
 *
 * Observe
 *
 * 14
 * already removed by 2
 *
 * 21
 * already removed by 3
 *
 * 28
 * already removed by 2
 *
 * 35
 * already removed by 5
 *
 * 42
 * already removed by 2
 *
 * First untouched multiple
 *
 * 49
 *
 * = p²
 *
 * Everything before p² already has
 * a smaller prime factor.
 *
 * This avoids redundant work.
 *
 * ============================================================================
 *
 * Why Naive Approaches Fail
 *
 * Method 1
 *
 * Check every number individually.
 *
 * Complexity
 *
 * O(N√N)
 *
 * With N = 5,000,000
 * this becomes too expensive.
 *
 * ------------------------------------------------------------
 *
 * Method 2
 *
 * Start marking from 2*p.
 *
 * Correct,
 * but repeats enormous work.
 *
 * Example
 *
 * 30
 *
 * gets removed by
 *
 * 2
 * 3
 * 5
 *
 * repeatedly.
 *
 * Starting from p² avoids these duplicates.
 *
 * ------------------------------------------------------------
 *
 * Method 3
 *
 * Process every number.
 *
 * Even composite p.
 *
 * Example
 *
 * p = 12
 *
 * All multiples already processed.
 *
 * Pure wasted work.
 *
 * ============================================================================
 *
 *                     🔴 COMMON INTERVIEW TRAPS
 *
 * ============================================================================
 *
 * Trap 1
 *
 * Forgetting n is exclusive.
 *
 * Count primes
 * LESS THAN n.
 *
 * ------------------------------------------------------------
 *
 * Trap 2
 *
 * Starting marking at
 *
 * 2*p
 *
 * instead of
 *
 * p*p.
 *
 * ------------------------------------------------------------
 *
 * Trap 3
 *
 * Forgetting
 *
 * n <= 2
 *
 * ------------------------------------------------------------
 *
 * Trap 4
 *
 * Using int multiplication blindly.
 *
 * p*p may overflow on larger sieve problems.
 *
 * Safer interview habit:
 *
 * (long)p * p
 *
 * even though this problem's constraints
 * still fit inside int.
 *
 * ============================================================================
 *
 *                    🛠 IMPLEMENTATION BLUEPRINT
 *
 * ============================================================================
 *
 * We assemble the code mechanically.
 *
 * Step 1
 *
 * Handle tiny inputs.
 *
 * Step 2
 *
 * Create boolean array.
 *
 * Step 3
 *
 * Assume every number >=2 is prime.
 *
 * Step 4
 *
 * Iterate p while
 *
 * p*p < n
 *
 * Step 5
 *
 * Skip already composite numbers.
 *
 * Step 6
 *
 * Mark multiples
 *
 * starting exactly at
 *
 * p*p
 *
 * Step 7
 *
 * Count remaining true entries.
 *
 * Step 8
 *
 * Return count.
 *
 * ============================================================================
 *
 *             Ultra-Compact Memory Scaffold
 * ============================================================================
 *
 * if small -> 0
 *
 * assume all prime
 *
 * for p until sqrt
 *
 *     if alive
 *
 *         mark p²,p²+p,...
 *
 * count alive
 *
 * return count
 *
 * ============================================================================
 */
public class CountPrimes {

    /**
     * ==========================================================
     * BRUTE FORCE
     * ==========================================================
     *
     * Idea
     * ----
     * Test every integer independently.
     *
     * Improvement over nothing,
     * but still expensive.
     *
     * Time
     * ----
     * O(N√N)
     *
     * Space
     * -----
     * O(1)
     *
     * Interview Preference
     * --------------------
     * Mention briefly,
     * then improve.
     */
    static class BruteForceSolution {

        public int countPrimes(int n) {

            int count = 0;

            for (int candidate = 2; candidate < n; candidate++) {

                if (isPrime(candidate)) {
                    count++;
                }
            }

            return count;
        }

        private boolean isPrime(int x) {

            if (x < 2)
                return false;

            for (int divisor = 2; divisor * divisor <= x; divisor++) {

                if (x % divisor == 0)
                    return false;
            }

            return true;
        }
    }

    /**
     * ==========================================================
     * IMPROVED
     * ==========================================================
     *
     * Improvement
     * -----------
     * Skip even candidates after handling prime 2.
     *
     * We still test primality independently,
     * but nearly halve the work.
     *
     * Limitation Fixed
     * ----------------
     * Avoid unnecessary work on even numbers.
     *
     * Remaining Bottleneck
     * --------------------
     * Every candidate is still checked separately.
     *
     * Complexity
     * ----------
     * Time:
     *      ~O(N√N / 2)
     *
     * Space:
     *      O(1)
     *
     * Interview Preference
     * --------------------
     * Mention only if interviewer asks for incremental
     * optimization before reaching the sieve.
     */
    static class ImprovedSolution {

        public int countPrimes(int n) {

            if (n <= 2)
                return 0;

            int count = 1;              // prime 2

            for (int candidate = 3;
                 candidate < n;
                 candidate += 2) {

                if (isPrime(candidate))
                    count++;
            }

            return count;
        }

        private boolean isPrime(int value) {

            if (value == 2)
                return true;

            if ((value & 1) == 0)
                return false;

            for (int divisor = 3;
                 divisor * divisor <= value;
                 divisor += 2) {

                if (value % divisor == 0)
                    return false;
            }

            return true;
        }
    }

    /**
     * ==========================================================
     * OPTIMAL (Interview Preferred)
     * ==========================================================
     *
     * Pattern
     * -------
     * Sieve of Eratosthenes
     *
     * Core Idea
     * ---------
     * Instead of repeatedly asking
     * "Is this number prime?"
     *
     * We proactively eliminate every composite exactly
     * when its smallest prime factor is discovered.
     *
     * Once finished,
     * whatever survives is prime.
     *
     * Invariant
     * ---------
     * Before processing p,
     * every multiple of every smaller prime
     * has already been eliminated.
     *
     * Therefore:
     *
     * if (isPrime[p])
     *
     * then p MUST be prime.
     *
     * Limitation Fixed
     * ----------------
     * Removes repeated divisor testing completely.
     *
     * Complexity
     * ----------
     *
     * Time
     *      O(N log log N)
     *
     * Space
     *      O(N)
     *
     * Interview Preference
     * --------------------
     * Always the expected solution.
     */
    static class OptimalSolution {

        public int countPrimes(int n) {

            if (n <= 2)
                return 0;

            boolean[] isComposite = new boolean[n];

            int limit = (int) Math.sqrt(n);

            for (int i = 2; i <= limit; i++) {

                if (!isComposite[i]) {

                    for (int j = i * i; j < n; j += i) {
                        isComposite[j] = true;
                    }
                }
            }

            int count = 0;

            for (int i = 2; i < n; i++) {
                if (!isComposite[i]) {
                    count++;
                }
            }

            return count;
        }
    }

    /**
     * ===============================================================================
     *                    SIEVE OF ERATOSTHENES — INTUITION & VISUALS
     * ===============================================================================
     *
     * GOAL
     * ----
     * Count all PRIME numbers strictly less than n.
     *
     * Instead of asking
     *
     *      "Is this number prime?"
     *
     * we reverse the thinking.
     *
     *      "Can I prove this number is composite?"
     *
     * If a smaller prime proves it composite,
     * mark it.
     *
     * Whatever survives until the end
     * must be prime.
     *
     *
     * ===============================================================================
     * CORE INVARIANT
     * ===============================================================================
     *
     * Before processing candidate prime p,
     *
     * every multiple of every SMALLER prime
     * has already been marked composite.
     *
     * Therefore,
     *
     * if p is still unmarked,
     *
     * p MUST be prime.
     *
     *
     * ===============================================================================
     * INITIAL STATE
     * ===============================================================================
     *
     * Initially every number is assumed prime.
     *
     *      2  3  4  5  6  7  8  9 10 11 12 ...
     *
     *      ✓  ✓  ✓  ✓  ✓  ✓  ✓  ✓  ✓  ✓  ✓
     *
     * ✓ means
     *
     *      "Not yet proven composite."
     *
     * Initially
     *
     *      isComposite[x] = false
     *
     * means
     *
     *      Unknown
     *
     * NOT
     *
     *      Prime
     *
     * Only after the sieve finishes,
     * every remaining false represents a prime.
     *
     *
     * ===============================================================================
     * OUTER LOOP vs INNER LOOP
     * ===============================================================================
     *
     * OUTER LOOP
     *
     * Chooses WHO gets to eliminate others.
     *
     *      2
     *      3
     *      4
     *      5
     *      6
     *      ...
     *
     * If a number is already composite,
     * it contributes nothing new.
     *
     * -------------------------------------------------------------------------------
     *
     * INNER LOOP
     *
     * Eliminates WHAT should disappear.
     *
     * For p = 2
     *
     *      4
     *      6
     *      8
     *      10
     *      12
     *      ...
     *
     * For p = 3
     *
     *      9
     *      12
     *      15
     *      18
     *      ...
     *
     * For p = 5
     *
     *      25
     *      30
     *      35
     *      40
     *      ...
     *
     * Outer Loop
     *      Discovers the next prime.
     *
     * Inner Loop
     *      Removes all multiples of that prime.
     *
     *
     * ===============================================================================
     * WHY START FROM i * i ?
     * ===============================================================================
     *
     * Example
     *
     *      p = 7
     *
     *      7 × 2 = 14   ← already removed by 2
     *      7 × 3 = 21   ← already removed by 3
     *      7 × 4 = 28   ← already removed by 2
     *      7 × 5 = 35   ← already removed by 5
     *      7 × 6 = 42   ← already removed by 2
     *
     *      ----------------------------------------
     *
     *      7 × 7 = 49   ← FIRST untouched multiple
     *      7 × 8 = 56
     *      7 × 9 = 63
     *
     * Every multiple before p² already contains
     * a smaller prime factor.
     *
     * Therefore,
     *
     *      Start marking from p².
     *
     *
     * ===============================================================================
     * WHY j += p ?
     * ===============================================================================
     *
     * Example
     *
     *      p = 5
     *
     * Need every remaining multiple of 5.
     *
     *      25
     *      30
     *      35
     *      40
     *      45
     *      50
     *
     * Difference
     *
     *      +5
     *      +5
     *      +5
     *      +5
     *
     * Therefore
     *
     *      j += p
     *
     * generates
     *
     *      p²
     *      p² + p
     *      p² + 2p
     *      p² + 3p
     *      ...
     *
     * which are exactly
     *
     *      p × p
     *      p × (p + 1)
     *      p × (p + 2)
     *      ...
     *
     * Every future multiple of p.
     *
     *
     * ===============================================================================
     * RESPONSIBILITY RULE (MOST IMPORTANT)
     * ===============================================================================
     *
     * Every composite has exactly ONE first owner.
     *
     *      30 = 2 × 3 × 5
     *           ^
     *           removed by 2
     *
     *      35 = 5 × 7
     *           ^
     *           removed by 5
     *
     *      77 = 7 × 11
     *           ^
     *           removed by 7
     *
     *      91 = 7 × 13
     *           ^
     *           removed by 7
     *
     * General Rule
     *
     *      Smallest Prime Factor
     *                │
     *                ▼
     *      Removes the composite first.
     *
     * This explains
     *
     * ✓ Correctness
     * ✓ Why composite numbers are skipped
     * ✓ Why marking starts from p²
     * ✓ Why the sieve works
     *
     *
     * ===============================================================================
     * WHY STOP AT √n ?
     * ===============================================================================
     *
     * Example
     *
     *      100
     *
     * Factor Pairs
     *
     *      1 × 100
     *      2 × 50
     *      4 × 25
     *      5 × 20
     *     10 × 10
     *     -----------------
     *     20 × 5
     *     25 × 4
     *     50 × 2
     *    100 × 1
     *
     * Meeting Point
     *
     *      √100 = 10
     *
     * Beyond √n,
     * factor pairs simply repeat.
     *
     * Therefore,
     * no new composite can be discovered.
     *
     *
     * ===============================================================================
     * VISUAL EXECUTION
     * ===============================================================================
     *
     * Initially
     *
     *      2 3 4 5 6 7 8 9 10 11 12 ...
     *      ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓  ✓  ✓
     *
     * Process 2
     *
     *      Remove
     *
     *      4 6 8 10 12 ...
     *
     * Process 3
     *
     *      Remove
     *
     *      9 12 15 18 ...
     *
     * Process 5
     *
     *      Remove
     *
     *      25 30 35 ...
     *
     * Remaining Survivors
     *
     *      2 3 5 7 11 13 17 ...
     *
     * These survivors are exactly the PRIME numbers.
     *
     *
     * ===============================================================================
     * BOOLEAN STATE TRANSITION
     * ===============================================================================
     *
     * Initially
     *
     *      false
     *
     * means
     *
     *      Unknown
     *
     *             │
     *             ▼
     *
     * Smaller prime divides it?
     *
     *        YES
     *         │
     *         ▼
     *
     *      true
     *
     *   (Composite)
     *
     *        NO
     *         │
     *         ▼
     *
     * Survives every elimination
     *
     *         │
     *         ▼
     *
     *       PRIME
     *
     *
     * ===============================================================================
     * INTERVIEW RECALL (30 Seconds)
     * ===============================================================================
     *
     * 1. Assume every number is prime.
     *
     * 2. Visit only numbers up to √n.
     *
     * 3. If a number is still unmarked,
     *    it is prime.
     *
     * 4. Start marking from p² because
     *    smaller multiples were already handled.
     *
     * 5. Mark every remaining multiple
     *    using j += p.
     *
     * 6. Every unmarked number left
     *    is a prime.
     *
     *
     * ===============================================================================
     * ONE-LINE INVARIANT
     * ===============================================================================
     *
     * Before processing prime p,
     * every multiple of every smaller prime has already been removed.
     *
     * Therefore,
     * if p is still unmarked,
     * p MUST be prime.
     * ===============================================================================
     **/

/**
 * ==========================================================
 * 🟣 INTERVIEW ARTICULATION
 * ==========================================================
 *
 * Q.
 * Why is an unmarked number guaranteed to be prime?
 *
 * Because every composite number possesses
 * a smallest prime factor.
 *
 * That smaller prime would already have marked it.
 *
 * Therefore if a number survives until its turn,
 * no smaller prime divides it.
 *
 * Hence it is prime.
 *
 * ----------------------------------------------------------
 *
 * Q.
 * Why stop at sqrt(n)?
 *
 * Every composite has one factor
 * not exceeding sqrt(number).
 *
 * Beyond sqrt,
 * every remaining composite has already
 * been eliminated.
 *
 * ----------------------------------------------------------
 *
 * Q.
 * Why begin at p²?
 *
 * Every smaller multiple:
 *
 * 2p
 * 3p
 * ...
 * (p−1)p
 *
 * already contains a smaller prime factor
 * and therefore has already been marked.
 *
 * ----------------------------------------------------------
 *
 * Q.
 * What breaks if we start from 2p?
 *
 * Correctness remains.
 *
 * Efficiency suffers because the same
 * composite gets marked repeatedly.
 *
 * ----------------------------------------------------------
 *
 * Q.
 * Is this in-place?
 *
 * No.
 *
 * The boolean array stores the current
 * elimination state.
 *
 * ----------------------------------------------------------
 *
 * Q.
 * Can this be streamed?
 *
 * No.
 *
 * Future decisions depend on remembering
 * which earlier multiples were removed.
 *
 * ----------------------------------------------------------
 *
 * Q.
 * When should this pattern NOT be used?
 *
 * - One very large primality query
 * - Huge values where O(N) memory
 *   is impossible
 * - Online/infinite streams
 *
 * Prefer:
 *
 * Trial Division
 * Miller-Rabin
 * Segmented Sieve
 *
 * depending on constraints.
 *
 * ==========================================================
 * 🎯 30-SECOND INTERVIEW RECALL
 * ==========================================================
 *
 * Pattern Trigger
 * ---------------
 * Need ALL primes below N.
 *
 * Core Invariant
 * --------------
 * Every processed prime has already removed
 * its multiples.
 *
 * Search Target
 * -------------
 * Remaining unmarked numbers.
 *
 * Discard Rule
 * ------------
 * Mark every multiple of the current prime.
 *
 * First Multiple
 * --------------
 * p²
 *
 * Stop Condition
 * --------------
 * p² >= n
 *
 * Common Trap
 * -----------
 * Starting at 2p.
 *
 * Edge Cases
 * ----------
 * n = 0
 * n = 1
 * n = 2
 *
 * Interview One-Liner
 * -------------------
 * Eliminate composites once;
 * survivors are primes.
 *
 * Re-Derivation Cue
 * -----------------
 * Every composite has a smallest
 * prime factor.
 *
 * Therefore every composite is removed
 * before its own turn.
 */

    /**
     * ==========================================================
     * 🔄 VARIATIONS & TWEAKS
     * ==========================================================
     *
     * The invariant remains:
     *
     *      "Every processed prime has already removed
     *       all of its multiples."
     *
     * Only the surrounding problem changes.
     *
     * ----------------------------------------------------------
     * Variation 1
     * ----------------------------------------------------------
     *
     * Return the list of primes instead of the count.
     *
     * Invariant
     * ---------
     * Unchanged.
     *
     * Change
     * ------
     * Instead of incrementing a counter,
     * collect surviving numbers.
     *
     * ----------------------------------------------------------
     * Variation 2
     * ----------------------------------------------------------
     *
     * Answer many prime queries.
     *
     * Example
     *
     * isPrime(499979)?
     * isPrime(123457)?
     * isPrime(8123)?
     *
     * Pre-compute one sieve.
     *
     * Query:
     *
     * O(1)
     *
     * ----------------------------------------------------------
     * Variation 3
     * ----------------------------------------------------------
     *
     * Need primes between L and R,
     * where R is huge.
     *
     * Example
     *
     * 10^12
     *
     * Use:
     *
     * Segmented Sieve.
     *
     * Same invariant.
     *
     * Different memory strategy.
     *
     * ----------------------------------------------------------
     * Variation 4
     * ----------------------------------------------------------
     *
     * Need prime factorization.
     *
     * Store
     *
     * smallestPrimeFactor[]
     *
     * instead of only boolean.
     *
     * Invariant changes slightly:
     *
     * first discoverer records itself
     * as smallest prime factor.
     *
     * ----------------------------------------------------------
     * Pattern Break Signals
     * ----------------------------------------------------------
     *
     * Need only one primality check.
     *
     * Large sparse values.
     *
     * Infinite stream.
     *
     * Memory too small for O(N).
     *
     * These indicate the sieve is no
     * longer the correct pattern.
     */

    /**
     * ==========================================================
     * ⚫ REINFORCEMENT PROBLEM 1
     * ==========================================================
     *
     * Problem
     * -------
     * Return all prime numbers less than n.
     *
     * Example
     * -------
     *
     * n = 15
     *
     * Output
     *
     * [2,3,5,7,11,13]
     *
     * Pattern
     * -------
     * SAME invariant.
     *
     * Instead of counting survivors,
     * collect survivors.
     *
     * Edge Cases
     * ----------
     *
     * n <= 2
     *
     * Empty list.
     *
     * Interview Trap
     * --------------
     *
     * Do NOT rerun primality tests.
     *
     * The sieve has already done that.
     */

    static class PrimeListSolution {

        public List<Integer> primesBelow(int n) {

            List<Integer> answer = new ArrayList<>();

            if (n <= 2)
                return answer;

            boolean[] prime = new boolean[n];

            Arrays.fill(prime, true);

            prime[0] = false;
            prime[1] = false;

            for (int p = 2;
                 (long) p * p < n;
                 p++) {

                if (!prime[p])
                    continue;

                for (int multiple = p * p;
                     multiple < n;
                     multiple += p) {

                    prime[multiple] = false;
                }
            }

            for (int value = 2;
                 value < n;
                 value++) {

                if (prime[value])
                    answer.add(value);
            }

            return answer;
        }
    }

    /**
     * ==========================================================
     * 🟣 INTERVIEW ARTICULATION
     * ==========================================================
     *
     * Only the output changes.
     *
     * The elimination process is identical.
     *
     * Counting and collecting are both
     * linear scans over surviving numbers.
     */

    /**
     * ==========================================================
     * ⚫ REINFORCEMENT PROBLEM 2
     * ==========================================================
     *
     * Problem
     * -------
     *
     * Return a boolean array where
     *
     * answer[i]
     *
     * tells whether i is prime.
     *
     * Useful for:
     *
     * • repeated lookups
     * • DP
     * • graph problems
     * • combinatorics
     *
     * Invariant
     * ---------
     *
     * Exactly identical.
     */

    static class PrimeLookupTable {

        public boolean[] buildPrimeTable(int n) {

            if (n <= 0)
                return new boolean[0];

            boolean[] prime = new boolean[n];

            if (n <= 2) {

                if (n > 0)
                    prime[0] = false;

                if (n > 1)
                    prime[1] = false;

                return prime;
            }

            Arrays.fill(prime, true);

            prime[0] = false;
            prime[1] = false;

            for (int p = 2;
                 (long) p * p < n;
                 p++) {

                if (!prime[p])
                    continue;

                for (int multiple = p * p;
                     multiple < n;
                     multiple += p) {

                    prime[multiple] = false;
                }
            }

            return prime;
        }
    }

    /**
     * ==========================================================
     * Edge Cases
     * ==========================================================
     *
     * n = 0
     *
     * []
     *
     * n = 1
     *
     * []
     *
     * n = 2
     *
     * []
     *
     * n = 3
     *
     * [2]
     *
     * n = 10
     *
     * [2,3,5,7]
     *
     * Interview Trap
     * --------------
     *
     * The returned array answers
     * primality in O(1),
     * but costs O(n) memory.
     */

    /**
     * ==========================================================
     * ⚫ REINFORCEMENT PROBLEM 3
     * ==========================================================
     *
     * Problem
     * -------
     *
     * Return the largest prime
     * strictly less than n.
     *
     * Example
     *
     * n = 20
     *
     * Answer
     *
     * 19
     *
     * n = 10
     *
     * Answer
     *
     * 7
     *
     * Invariant
     * ---------
     *
     * Still unchanged.
     *
     * Only the final scan direction changes.
     */

    static class LargestPrimeBelow {

        public int largestPrimeLessThan(int n) {

            if (n <= 2)
                return -1;

            boolean[] prime = new boolean[n];

            Arrays.fill(prime, true);

            prime[0] = false;
            prime[1] = false;

            for (int p = 2;
                 (long) p * p < n;
                 p++) {

                if (!prime[p])
                    continue;

                for (int multiple = p * p;
                     multiple < n;
                     multiple += p) {

                    prime[multiple] = false;
                }
            }

            for (int i = n - 1;
                 i >= 2;
                 i--) {

                if (prime[i])
                    return i;
            }

            return -1;
        }
    }

    /**
     * ==========================================================
     * 🧩 RELATED PROBLEMS
     * ==========================================================
     *
     * These problems are closely related to Count Primes.
     *
     * Some preserve the invariant completely.
     * Some modify it.
     * Some require recognizing when the pattern breaks.
     *
     * ==========================================================
     * Related Problem 1
     * ==========================================================
     *
     * Problem
     * -------
     * Determine whether a single integer n is prime.
     *
     * Example
     * -------
     * 29 -> true
     * 30 -> false
     *
     * Invariant
     * ---------
     * Broken.
     *
     * We no longer need to eliminate every composite.
     * We only need to determine whether one number has
     * a divisor not exceeding √n.
     *
     * Pattern
     * -------
     * Trial Division
     *
     * Time
     * ----
     * O(√n)
     *
     * Space
     * -----
     * O(1)
     */

    static class IsPrimeSolution {

        public boolean isPrime(int n) {

            if (n < 2)
                return false;

            if (n == 2)
                return true;

            if ((n & 1) == 0)
                return false;

            for (int divisor = 3;
                 (long) divisor * divisor <= n;
                 divisor += 2) {

                if (n % divisor == 0)
                    return false;
            }

            return true;
        }
    }

    /**
     * Edge Cases
     * ----------
     * 0
     * 1
     * 2
     * Even numbers
     *
     * Interview Note
     * --------------
     * Don't build a sieve for one query.
     * Trial division is simpler and uses constant memory.
     */

    /**
     * ==========================================================
     * Related Problem 2
     * ==========================================================
     *
     * Problem
     * -------
     * Find the smallest prime greater than or equal to n.
     *
     * Example
     * -------
     * 14 -> 17
     * 17 -> 17
     *
     * Invariant
     * ---------
     * Broken.
     *
     * We repeatedly perform primality testing.
     *
     * Pattern
     * -------
     * Increment + Trial Division
     */

    static class NextPrimeSolution {

        public int nextPrime(int n) {

            if (n <= 2)
                return 2;

            if ((n & 1) == 0)
                n++;

            while (true) {

                if (isPrime(n))
                    return n;

                n += 2;
            }
        }

        private boolean isPrime(int value) {

            if (value == 2)
                return true;

            if ((value & 1) == 0)
                return false;

            for (int divisor = 3;
                 (long) divisor * divisor <= value;
                 divisor += 2) {

                if (value % divisor == 0)
                    return false;
            }

            return true;
        }
    }

    /**
     * Edge Case
     * ---------
     * n <= 2
     *
     * Interview Note
     * --------------
     * This is NOT a sieve problem because
     * we are searching forward for only one answer.
     */

    /**
     * ==========================================================
     * Related Problem 3
     * ==========================================================
     *
     * Problem
     * -------
     * Return all prime factors of n.
     *
     * Example
     * -------
     * 84
     *
     * Output
     *
     * [2,2,3,7]
     *
     * Invariant
     * ---------
     * Modified.
     *
     * Instead of removing multiples globally,
     * we repeatedly remove factors from one number.
     */

    static class PrimeFactorization {

        public List<Integer> factorize(int n) {

            List<Integer> answer = new ArrayList<>();

            while ((n & 1) == 0) {
                answer.add(2);
                n /= 2;
            }

            for (int divisor = 3;
                 (long) divisor * divisor <= n;
                 divisor += 2) {

                while (n % divisor == 0) {
                    answer.add(divisor);
                    n /= divisor;
                }
            }

            if (n > 1)
                answer.add(n);

            return answer;
        }
    }

/**
 * Edge Case
 * ---------
 * Prime number
 *
 * Example
 * -------
 * 13
 *
 * Output
 *
 * [13]
 *
 * Interview Note
 * --------------
 * Remaining value after trial division,
 * if greater than one,
 * must itself be prime.
 */

/**
 * ==========================================================
 * 🧠 MASTERY CHECKLIST
 * ==========================================================
 *
 * □ Can I state the invariant without looking?
 *
 *      Every processed prime has already removed
 *      all of its multiples.
 *
 * ----------------------------------------------------------
 *
 * □ What is the search target?
 *
 *      Surviving (unmarked) numbers.
 *
 * ----------------------------------------------------------
 *
 * □ Why does an unmarked number imply prime?
 *
 *      Otherwise its smallest prime factor
 *      would already have removed it.
 *
 * ----------------------------------------------------------
 *
 * □ Why start from p²?
 *
 *      Every smaller multiple already has
 *      a smaller prime factor.
 *
 * ----------------------------------------------------------
 *
 * □ Why stop at √n?
 *
 *      Larger composites always have
 *      a smaller complementary factor.
 *
 * ----------------------------------------------------------
 *
 * □ Complexity?
 *
 *      Time:
 *      O(n log log n)
 *
 *      Space:
 *      O(n)
 *
 * ----------------------------------------------------------
 *
 * □ Common Bugs
 *
 *      Forgetting n is exclusive.
 *
 *      Forgetting 0 and 1.
 *
 *      Starting from 2p.
 *
 *      Processing composite p.
 *
 *      Integer overflow in p*p.
 *
 * ----------------------------------------------------------
 *
 * □ Debugging Readiness
 *
 *      If a composite survives,
 *      ask:
 *
 *      Which smallest prime factor
 *      failed to mark it?
 *
 *      This immediately narrows
 *      the bug to one sieve iteration.
 *
 * ----------------------------------------------------------
 *
 * □ Variant Readiness
 *
 *      Count primes ✔
 *
 *      List primes ✔
 *
 *      Prime lookup table ✔
 *
 *      Largest prime below n ✔
 *
 *      Segmented sieve (concept) ✔
 *
 * ----------------------------------------------------------
 *
 * □ Pattern Boundary
 *
 *      One query?
 *          Trial Division.
 *
 *      Many queries?
 *          Sieve.
 *
 *      Huge interval?
 *          Segmented Sieve.
 *
 *      Massive integers?
 *          Miller-Rabin.
 *
 * ==========================================================
 */


    /**
     * ==========================================================
     * SELF-VERIFYING TESTS
     * ==========================================================
     *
     * Philosophy
     * ----------
     * Printing output is useful for humans,
     * but interviews and production code require
     * automatic verification.
     *
     * Each test below validates one important
     * invariant or edge condition.
     */

    private static void assertEquals(int expected,
                                     int actual,
                                     String message) {

        if (expected != actual) {
            throw new AssertionError(
                    message +
                            "\nExpected : " + expected +
                            "\nActual   : " + actual);
        }
    }

    private static void assertTrue(boolean condition,
                                   String message) {

        if (!condition) {
            throw new AssertionError(message);
        }
    }

    private static void assertListEquals(List<Integer> expected,
                                         List<Integer> actual,
                                         String message) {

        if (!expected.equals(actual)) {
            throw new AssertionError(
                    message +
                            "\nExpected : " + expected +
                            "\nActual   : " + actual);
        }
    }

    public static void main(String[] args) {

        OptimalSolution optimal = new OptimalSolution();

        /*
         * ------------------------------------------------------
         * Happy Path
         * ------------------------------------------------------
         */

        assertEquals(
                4,
                optimal.countPrimes(10),
                "Primes below 10 should be 2,3,5,7");

        assertEquals(
                8,
                optimal.countPrimes(20),
                "Primes below 20");

        assertEquals(
                25,
                optimal.countPrimes(100),
                "Known mathematical result");

        /*
         * ------------------------------------------------------
         * Boundary Cases
         * ------------------------------------------------------
         */

        assertEquals(
                0,
                optimal.countPrimes(0),
                "No primes below 0");

        assertEquals(
                0,
                optimal.countPrimes(1),
                "No primes below 1");

        assertEquals(
                0,
                optimal.countPrimes(2),
                "No primes strictly below 2");

        assertEquals(
                1,
                optimal.countPrimes(3),
                "Only prime below 3 is 2");

        /*
         * ------------------------------------------------------
         * Interview Trap
         * ------------------------------------------------------
         *
         * n is exclusive.
         */

        assertEquals(
                4,
                optimal.countPrimes(11),
                "11 itself must not be counted");

        /*
         * ------------------------------------------------------
         * Brute Force Cross Check
         * ------------------------------------------------------
         */

        BruteForceSolution brute = new BruteForceSolution();

        for (int n = 0; n <= 200; n++) {

            assertEquals(
                    brute.countPrimes(n),
                    optimal.countPrimes(n),
                    "Brute force mismatch at n = " + n);
        }

        /*
         * ------------------------------------------------------
         * Improved Solution Cross Check
         * ------------------------------------------------------
         */

        ImprovedSolution improved = new ImprovedSolution();

        for (int n = 0; n <= 200; n++) {

            assertEquals(
                    improved.countPrimes(n),
                    optimal.countPrimes(n),
                    "Improved solution mismatch at n = " + n);
        }

        /*
         * ------------------------------------------------------
         * Reinforcement Problem 1
         * ------------------------------------------------------
         */

        PrimeListSolution listSolution =
                new PrimeListSolution();

        assertListEquals(
                Arrays.asList(2, 3, 5, 7),
                listSolution.primesBelow(10),
                "Prime list incorrect");

        assertListEquals(
                Collections.emptyList(),
                listSolution.primesBelow(2),
                "Prime list below 2");

        /*
         * ------------------------------------------------------
         * Reinforcement Problem 2
         * ------------------------------------------------------
         */

        PrimeLookupTable lookup =
                new PrimeLookupTable();

        boolean[] table = lookup.buildPrimeTable(20);

        assertTrue(table[2], "2 should be prime");
        assertTrue(table[3], "3 should be prime");
        assertTrue(!table[4], "4 should be composite");
        assertTrue(table[5], "5 should be prime");
        assertTrue(!table[9], "9 should be composite");
        assertTrue(table[19], "19 should be prime");

        /*
         * ------------------------------------------------------
         * Reinforcement Problem 3
         * ------------------------------------------------------
         */

        LargestPrimeBelow largest =
                new LargestPrimeBelow();

        assertEquals(
                19,
                largest.largestPrimeLessThan(20),
                "Largest prime below 20");

        assertEquals(
                7,
                largest.largestPrimeLessThan(10),
                "Largest prime below 10");

        assertEquals(
                -1,
                largest.largestPrimeLessThan(2),
                "No prime below 2");

        /*
         * ------------------------------------------------------
         * Related Problem 1
         * ------------------------------------------------------
         */

        IsPrimeSolution isPrime =
                new IsPrimeSolution();

        assertTrue(
                isPrime.isPrime(97),
                "97 should be prime");

        assertTrue(
                !isPrime.isPrime(91),
                "91 = 7 × 13");

        /*
         * ------------------------------------------------------
         * Related Problem 2
         * ------------------------------------------------------
         */

        NextPrimeSolution next =
                new NextPrimeSolution();

        assertEquals(
                17,
                next.nextPrime(14),
                "Next prime after 14");

        assertEquals(
                17,
                next.nextPrime(17),
                "17 is already prime");

        /*
         * ------------------------------------------------------
         * Related Problem 3
         * ------------------------------------------------------
         */

        PrimeFactorization factorization =
                new PrimeFactorization();

        assertListEquals(
                Arrays.asList(2, 2, 3, 7),
                factorization.factorize(84),
                "Prime factorization incorrect");

        assertListEquals(
                Arrays.asList(13),
                factorization.factorize(13),
                "Prime number factorization incorrect");

        /*
         * ------------------------------------------------------
         * Larger Regression Sample
         * ------------------------------------------------------
         */

        assertEquals(
                168,
                optimal.countPrimes(1000),
                "Known count of primes below 1000");

        System.out.println("======================================");
        System.out.println("All self-verifying tests passed.");
        System.out.println("Optimal Solution : O(n log log n)");
        System.out.println("Space            : O(n)");
        System.out.println("Pattern          : Sieve of Eratosthenes");
        System.out.println("======================================");
    }
}

